### ISSUE TITLE
ExcelDnaPack.exe failed to execute

### ISSUE THREAD

**Issue by vincentbeaulieu** [Excel-DNA/ExcelDna#118]
I'm running the program without any parameters and i'm not getting the standard help page that i receive on other computers.
My ExcelDna version is : 0.33.9
I'm trying to execute ExcelDna.exe on my computer the program stops working and crash and starts debugging the program with Visual Studio. When I close the debug window, i get the following errors in event viewer (i used google translate):

```
Name of the application failing ExcelDnaPack.exe, version: 0.33.9.1, time stamp: 0x55f09616
Name of the failing module: mscorwks.dll, version: 2.0.50727.8745, time stamp: 0x573d296c
Exception code: 0xc0000005
Error offset: 0x0000000000677463
Failed process ID: 0x% 9
Time of start of application failing: 0x% 10
Path of the failing application:% 11
Path of the failing module:% 12
Report ID:% 13
Full name of the failing package:% 14
Application ID for the failing package:% 15
```

`.NET Runtime version 2.0.50727.8745 - Unrecoverable Failure of Runtime Error (00007FF84ACA0D3E) (80131506)`

I'm using .Net 4 with Nugget with the following parameters:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Excel-DNA" version="0.33.9" targetFramework="net40" />
  <package id="ExcelDna.AddIn" version="0.33.9" targetFramework="net40" />
  <package id="ExcelDna.Integration" version="0.33.9" targetFramework="net40" />
</packages>
```

Thank you for your help!

**Comment by govert** [comment]
It's running ExcelDnaPack.exe under .NET 2.0, which might be a problem if you have an old version or don't have it at all. The issue is fixed in the current pre-release version of the NuGet package (it puts an ExcelDnaPack.exe.config next to ExcelDnaPack.exe).

I suggest you install the pre-release package from NuGet, currently v. 0.34.4-rc3.

Otherwise you can take the content from here https://github.com/Excel-DNA/ExcelDna/blob/master/Source/ExcelDnaPack/app.config and put it into a file called ExcelDnaPack.exe.config into your `packages\ExcelDna.AddIn.0.33.9\tools` directory.

**Comment by vincentbeaulieu** [comment]
Thanks !

I modified the config file tho by replacing `<supportedRuntime version="v2.0.50727"/>` by `<supportedRuntime version="v2.0.50727.8745"/>` which corresponded to the error in my event viewer.

I still have problem to make the thing work perfectly but at least the program is working !

Thanks !
