### ISSUE TITLE
Clean Build or Rebuild Solution give Unautherized Exception

### ISSUE THREAD

**Issue by Rand-Random** [Excel-DNA/ExcelDna#135]
I have updated to the latest version of ExcelDna and now I am receiving "Access denied." when the Clean Build tries to delete the xxxx.dna files.

I have noticed that the xxxx.dna files are created with read-only flag.

**Comment by caioproiete** [comment]
@Rand-Random When installing ExcelDna, the files are not read-only. I'm guessing something on your computer is marking the files that way. Maybe it is your source control? (TFS used to do that)

Could you post your complete MSBuild log here?

I'll work on a fix for it, anyway.

**Comment by Rand-Random** [comment]
But source control has nothing to do in bin/debug, bin/release folders, and the file in there are marked as read-only. I would definetly question, why the build process creates a read-only file in the first place.

Here my build output.

`1>------ Rebuild All started: Project: ServerCore, Configuration: Debug Any CPU ------
1>  ServerCore -> xxxx\ServerCore.dll
1>          1 File(s) copied.
2>------ Rebuild All started: Project: Server, Configuration: Debug Any CPU ------
2>  Server -> xxxx\Server.dll
2>          1 File(s) copied.
3>------ Rebuild All started: Project: OfficeHelper, Configuration: Debug Any CPU ------
3>  OfficeHelper -> xxxx\OfficeHelper.dll
3>          1 File(s) copied.
4>------ Rebuild All started: Project: ExcelHelper, Configuration: Debug Any CPU ------
4>  ExcelHelper -> xxxx\ExcelHelper.dll
5>------ Rebuild All started: Project: RTDServer, Configuration: Debug Any CPU ------
5>  RTDServer -> xxxx\RTDServer.dll
3>          1 File(s) copied.
6>------ Rebuild All started: Project: ExcelAddin, Configuration: Debug Any CPU ------
6>          1 File(s) copied.
6>  ---
6>  ExcelDnaBuild: ---
6>MSBUILD : ExcelDnaBuild error DNA573840453: xxxx\ExcelAddin-AddIn.dna' is denied.
6>MSBUILD : ExcelDnaBuild error DNA573840453: System.UnauthorizedAccessException: Access to the path 'xxxx\ExcelAddin-AddIn.dna' is denied.
6>MSBUILD : ExcelDnaBuild error DNA573840453:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
6>MSBUILD : ExcelDnaBuild error DNA573840453:    at System.IO.File.InternalDelete(String path, Boolean checkHost)
6>MSBUILD : ExcelDnaBuild error DNA573840453:    at System.IO.File.Delete(String path)
6>MSBUILD : ExcelDnaBuild error DNA573840453:    at ExcelDna.AddIn.Tasks.Utils.ExcelDnaPhysicalFileSystem.DeleteFile(String sourceFileName)
6>MSBUILD : ExcelDnaBuild error DNA573840453:    at ExcelDna.AddIn.Tasks.CleanExcelAddIn.DeleteAddInFiles(BuildItemSpec[] buildItemsForDnaFiles)
6>MSBUILD : ExcelDnaBuild error DNA573840453:    at ExcelDna.AddIn.Tasks.CleanExcelAddIn.Execute()
========== Rebuild All: 5 succeeded, 1 failed, 0 skipped ==========`

Is it possible to update nuget packages with this fix?

**Comment by govert** [comment]
@Rand-Random The behaviour you report does not happen on my  machine.
What can I do to figure out why our machines behave differently in this respect?

**Comment by govert** [comment]
@Rand-Random If you start with a fresh solution with a new Class Library project, and then in stall the ExcelDna.AddIn package from NuGet, do you see this happening in that case too?

**Comment by Rand-Random** [comment]
"\packages\ExcelDna.AddIn.0.34.6\tools\ExcelDna.xll" as read-only.
And you will receive read-only files in your bin/debug folder, though for some unknown reasons in my newly created test project the .packed.xll files also get created as read-only where in my real add-in project the packed dont have it.

And since the packed.xll files are also read-only some "packening" results in the following error:
(xll files still got created at this point, but as mentioned with read-only)

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The command ""c:\users\rfa\documents\visual studio 2017\Projects\ClassLibrary1\packages\ExcelDna.AddIn.0.34.6\tools\ExcelDnaPack.exe" "bin\Debug\ClassLibrary1-AddIn.dna" /Y  /O "bin\Debug\ClassLibrary1-AddIn-packed.xll"" exited with code 1.	ClassLibrary1
```

Couldnt figure out why they differ.

**Comment by Rand-Random** [comment]
So maybe change the code:

`        public void CopyFile(string sourceFileName, string destFileName, bool overwrite)
        {
            if (overwrite)
            {
                var fileInfo = new FileInfo(destFileName);
                if (fileInfo.Exists && fileInfo.IsReadOnly)
                {
                    fileInfo.IsReadOnly = false;
                }
            }

            File.Copy(sourceFileName, destFileName, overwrite);
        }`

to

`        public void CopyFile(string sourceFileName, string destFileName, bool overwrite)
        {
            if (overwrite)
            {
                var fileInfo = new FileInfo(destFileName);
                if (fileInfo.Exists && fileInfo.IsReadOnly)
                {
                    fileInfo.IsReadOnly = false;
                }
            }

            File.Copy(sourceFileName, destFileName, overwrite);
            var destFileInfo = new FileInfo(destFileName); //file copy, also "copies" the read-only flag - remove it
            if (destFileInfo.IsReadOnly)
                destFileInfo.IsReadOnly = false;
        }`

**Comment by caioproiete** [comment]
> But source control has nothing to do in bin/debug, bin/release folders, and the file in there are marked as read-only. I would definetly question, why the build process creates a read-only file in the first place.

@Rand-Random Something on your machine is marking the source files (e.g. `xxx\ExcelAddin-AddIn.dna`) as read-only, and when we copy the files to the output folder (e.g. `bin\Debug`) it brings the read-only flag with it, and then causes a rebuild to fail the next time, when it tries to clean files in the output folder.

I've seen this kind of behavior before with source control systems such as TFS and SourceSafe, that marks files as read-only by default, until you check the files out from source control, thus that would be my guess of what is causing this for you.

[I've put a fix in place](https://github.com/Excel-DNA/ExcelDna/pull/136/commits/3770eecc077621f4240749e8aaa8a381691faaf4v) which will remove the read-only flag from a file, before trying to delete it, which should resolve these build errors you're getting.

Please take it for a spin and let is know if that fixes the issue.

**Comment by Rand-Random** [comment]
@caioproiete It seems you missed that

> (And just to clarify, yes those 2 files are read-only in my case because of source control, maybe upon building and copying those files into bin/debug they keep the read-only flag?)

I just simply didnt know that the read-only flag is kept intact when you copy a file.
I would prefer that the read-only flag gets removed upon copying the file so that my bin\debug folder doesnt have the read-only file to begin with.
Thats why I suggested the change in the method CopyFile.

How would you suggest me testing the change, download source and build and than replace nuget package?

**Comment by caioproiete** [comment]
@Rand-Random Indeed, I missed that part. Great that you found the culprit!

I agree with you that it would be better to have the files in `bin\Debug` folder not read-only, but I'm not 100% sure if that should be ExcelDna's job... Really, your source control shouldn't be doing that in the first place... Perhaps it is time for you to move onto something better, like Git or something? :stuck_out_tongue_winking_eye: 

Jokes aside, I'll have a think about that, but at first glance it seems like the way to go about that would be to modify the `CopyFile` method on `ExcelDnaPhysicalFileSystem` to no use `File.Copy`, and instead, open a `BinaryReader` to the source, and a `BinaryWriter` to the destination, and copy the contents of the file, effectively creating a file from scratch, without bringing any of the attributes that the file has. Feel free to send a PR, if you want.

As for testing, I suggest you download ExcelDna's source code, build it (you only need to build the project `ExcelDna.AddIn.Tasks`, really), and then (before you open your own project in Visual Studio) replace the `ExcelDna.AddIn.Tasks.dll` in your project. Then finally open your project on Visual Studio, and try to rebuild a few times, checking that the read-only flag is set in the source files and files are being correctly deleted during the clean on rebuild.

**Comment by Rand-Random** [comment]
To give an update:
I reverted to old version, because this issue #137 makes my boss nervous.

About the source control, we are using SVN with locking required.
This makes all files read-only, and when I desire to edit a file I need to exclusivly lock it for me.
If someone from my Team wants to edit the same file, we need to discuss when he gets it from me, can happen that someone cannot edit a file for a week since someone else cannot commit it since its WIP.

Just to give you a glimpse of the horror I am working with. :)
I would totally love to work with Git (or atleast without the locking mechanism), but here merging is bad and locking is good.

**Comment by caioproiete** [comment]
This issue is resolved by #139
