### ISSUE TITLE
NuGet package creates Debug external program path with %1

### ISSUE THREAD

**Issue by govert** [Excel-DNA/ExcelDna#161]
The current NuGet package (sometimes?) sets path to the external program in the Debug settings to include a '%1' which causes the following error:

> 
> ---------------------------
> Microsoft Visual Studio
> ---------------------------
> Visual Studio cannot debug because the debug target 'C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE %1' is not an EXE file.
> ---------------------------
> OK   
> ---------------------------
>

**Comment by govert** [comment]
Rather, I guess it is Build Task that that sets the wrong path.

**Comment by govert** [comment]
Sorry, I guess it is still the install.ps1 setting this...
Not sure how it went wrong.

**Comment by govert** [comment]
I'm getting confused between the v 0.34 and newer changes. The new build tasks should fix this, but maybe we can set it to the path without the %1 in the install.ps1 already.

**Comment by caioproiete** [comment]
> I'm getting confused between the v 0.34 and newer changes. The new build tasks should fix this, but maybe we can set it to the path without the %1 in the install.ps1 already.

I've seen this before with Office 2016, and I believe it has to do with the way the `EXCEL.EXE` was discovered in the Powershell script, reading from the registry in `HKEY_CLASSES_ROOT\Excel.XLL\shell\Open\command`.

[The way that the `EXCEL.EXE` path is constructed is different and fixes this](https://github.com/Excel-DNA/ExcelDna/blob/master/Source/ExcelDna.AddIn.Tasks/Utils/ExcelDetector.cs#L104).

The `install.ps1` script no longer has any code to detect Excel, so nothing to fix there, unless you rollback to a previous version to apply a fix there and do an intermediary release before the release with the build task.

**Comment by govert** [comment]
OK sorry, I got completely confused between the versions.
I was surprised to find out that the current NuGet package doesn't work on a default Excel install - I had thought the problem was only something on my computer.

**Comment by dominhtri1995** [comment]
I'm sorry but how do we fix this problem? I try to remove the %1 in the path but it still doesnt work

**Comment by govert** [comment]
@dominhtri1995  I've never had a problem after removing the %1. Is the path to the Excel executable correct? What happens when you try to debug after removing the %1?

**Comment by govert** [comment]
I pushed a first test of version 0.35 which included the new style debugger setting.

**Comment by rvnlord** [comment]
Answer to these issues is to put in Properties > Debug:
Launch External Program: C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE
Arguments: "<YouExcelAddInName>-AddIn64.xll"
Otherwise it won't stop at breakpoints (as of v0.34.6)

**Comment by govert** [comment]
@rvnlord This should be fixed in the latest pre-release package, version 0.35.1-beta2. If not, please let me know.
